add_newline = true

palette = "catppuccin_macchiato"

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$line_break\
$jobs\
$python\
$character"""

right_format = """
$singularity\
$kubernetes\
$vcsh\
$fossil_branch\
$git_branch\
$git_commit\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$c\
$cpp\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$buf\
$conda\
$pixi\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$crystal\
$cmd_duration\
$custom\
$status\
$os\
$battery\
$time"""

[fill]
symbol = ' '

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[directory]
read_only = " 󰌾"
style = "bold lavender"
home_symbol = " ~"
truncation_length = 3
format = "[$path]($style)[$read_only]($style)"

[character]
success_symbol = "[[󰄛](green) ❯](peach)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[status]
disabled = false
map_symbol = true
success_symbol = "[✓](green)"
format = "$common_symbol "
style = "text"

[git_branch]
symbol = "  "
format = "[$symbol$branch]($style)"
style = "yellow"

[git_status]
style = "overlay1"
ahead = "↑"
behind = "↓"
conflicted = "[✗$count](red)"
staged = "[+$count](green)"
modified = "[~$count](yellow)"
renamed = "[»$count](mauve)"
untracked = "[?$count](subtext1)"
deleted = "[-$count](maroon)"
stashed = "[≡$count](sky)"
format = "[($conflicted$staged$modified$renamed$untracked$deleted [$ahead_behind]($blue) $stashed)]($style)"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "surface0"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
symbol = "  🐍"
format = "[$symbol$virtualenv ($version)]($style) "
style = "#a6e3a1"
disabled = false

[hostname]
ssh_symbol = "󰢹 "

[gcloud]
symbol = "  "
disabled = true

[jobs]
symbol = "⚙"
style = "#f5c2e7"
threshold = 1
disabled = false
format = "[$symbol$number]($style) "

[aws]
symbol = "  "

[buf]
symbol = " "

[bun]
symbol = " "

[c]
symbol = " "

[cpp]
symbol = " "

[cmake]
symbol = " "

[conda]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "

[deno]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

[fossil_branch]
symbol = " "

[git_commit]
tag_symbol = "  "

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[ocaml]
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CachyOS = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
Nobara = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

[pixi]
symbol = "󰏗 "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = "󱘗 "

[scala]
symbol = " "

[swift]
symbol = " "

[zig]
symbol = " "

[gradle]
symbol = " "
